export const BLAZER_LIST_REQUEST = 'BLAZER_LIST_REQUEST';
export const BLAZER_LIST_SUCCESS = 'BLAZER_LIST_SUCCESS';
export const BLAZER_LIST_FAIL = 'BLAZER_LIST_FAIL';

export const BLAZER_DETAILS_REQUEST = 'BLAZER_DETAILS_REQUEST';
export const BLAZER_DETAILS_SUCCESS = 'BLAZER_DETAILS_SUCCESS';
export const BLAZER_DETAILS_FAIL = 'BLAZER_DETAILS_FAIL';

export const BLAZER_CREATE_REQUEST = 'BLAZER_CREATE_REQUEST';
export const BLAZER_CREATE_SUCCESS = 'BLAZER_CREATE_SUCCESS';
export const BLAZER_CREATE_FAIL = 'BLAZER_CREATE_FAIL';
export const BLAZER_CREATE_RESET = 'BLAZER_CREATE_RESET';

export const BLAZER_REVIEW_CREATE_REQUEST = 'BLAZER_REVIEW_CREATE_REQUEST';
export const BLAZER_REVIEW_CREATE_SUCCESS = 'BLAZER_REVIEW_CREATE_SUCCESS';
export const BLAZER_REVIEW_CREATE_FAIL = 'BLAZER_REVIEW_CREATE_FAIL';
export const BLAZER_REVIEW_CREATE_RESET = 'BLAZER_REVIEW_CREATE_RESET';

export const BLAZER_UPDATE_REQUEST = 'BLAZER_UPDATE_REQUEST';
export const BLAZER_UPDATE_SUCCESS = 'BLAZER_UPDATE_SUCCESS';
export const BLAZER_UPDATE_FAIL = 'BLAZER_UPDATE_FAIL';
export const BLAZER_UPDATE_RESET = 'BLAZER_UPDATE_RESET';

export const BLAZER_DELETE_REQUEST = 'BLAZER_DELETE_REQUEST';
export const BLAZER_DELETE_SUCCESS = 'BLAZER_DELETE_SUCCESS';
export const BLAZER_DELETE_FAIL = 'BLAZER_DELETE_FAIL';
export const BLAZER_DELETE_RESET = 'BLAZER_DELETE_RESET';

export const BLAZER_CATEGORY_LIST_REQUEST = 'BLAZER_CATEGORY_LIST_REQUEST';
export const BLAZER_CATEGORY_LIST_SUCCESS = 'BLAZER_CATEGORY_LIST_SUCCESS';
export const BLAZER_CATEGORY_LIST_FAIL = 'BLAZER_CATEGORY_LIST_FAIL';