export const CART_TSHIRT_ADD_ITEM = 'CART_TSHIRT_ADD_ITEM';
export const CART_TSHIRT_REMOVE_ITEM = 'CART_TSHIRT_REMOVE_ITEM';
export const CART_TSHIRT_SAVE_SHIPPING_ADDRESS = 'CART_TSHIRT_SAVE_SHIPPING_ADDRESS';
export const CART_TSHIRT_SAVE_PAYMENT_METHOD = 'CART_TSHIRT_SAVE_PAYMENT_METHOD';
export const CART_TSHIRT_EMPTY = 'CART_TSHIRT_EMPTY';
export const CART_TSHIRT_ADD_ITEM_FAIL = 'CART_TSHIRT_ADD_ITEM_FAIL';