export const CART_CASUALSHIRT_ADD_ITEM = 'CART_CASUALSHIRT_ADD_ITEM';
export const CART_CASUALSHIRT_REMOVE_ITEM = 'CART_CASUALSHIRT_REMOVE_ITEM';
export const CART_CASUALSHIRT_SAVE_SHIPPING_ADDRESS = 'CART_CASUALSHIRT_SAVE_SHIPPING_ADDRESS';
export const CART_CASUALSHIRT_SAVE_PAYMENT_METHOD = 'CART_CASUALSHIRT_SAVE_PAYMENT_METHOD';
export const CART_CASUALSHIRT_EMPTY = 'CART_CASUALSHIRT_EMPTY';
export const CART_CASUALSHIRT_ADD_ITEM_FAIL = 'CART_CASUALSHIRT_ADD_ITEM_FAIL';