export const CART_DHOTIS_ADD_ITEM = 'CART_DHOTIS_ADD_ITEM';
export const CART_DHOTIS_REMOVE_ITEM = 'CART_DHOTIS_REMOVE_ITEM';
export const CART_DHOTIS_SAVE_SHIPPING_ADDRESS = 'CART_DHOTIS_SAVE_SHIPPING_ADDRESS';
export const CART_DHOTIS_SAVE_PAYMENT_METHOD = 'CART_DHOTIS_SAVE_PAYMENT_METHOD';
export const CART_DHOTIS_EMPTY = 'CART_DHOTIS_EMPTY';
export const CART_DHOTIS_ADD_ITEM_FAIL = 'CART_DHOTIS_ADD_ITEM_FAIL';