export const CART_FORMALSHIRT_ADD_ITEM = 'CART_FORMALSHIRT_ADD_ITEM';
export const CART_FORMALSHIRT_REMOVE_ITEM = 'CART_FORMALSHIRT_REMOVE_ITEM';
export const CART_FORMALSHIRT_SAVE_SHIPPING_ADDRESS = 'CART_FORMALSHIRT_SAVE_SHIPPING_ADDRESS';
export const CART_FORMALSHIRT_SAVE_PAYMENT_METHOD = 'CART_FORMALSHIRT_SAVE_PAYMENT_METHOD';
export const CART_FORMALSHIRT_EMPTY = 'CART_FORMALSHIRT_EMPTY';
export const CART_FORMALSHIRT_ADD_ITEM_FAIL = 'CART_FORMALSHIRT_ADD_ITEM_FAIL';