export const CART_BLAZER_ADD_ITEM = 'CART_BLAZER_ADD_ITEM';
export const CART_BLAZER_REMOVE_ITEM = 'CART_BLAZER_REMOVE_ITEM';
export const CART_BLAZER_SAVE_SHIPPING_ADDRESS = 'CART_BLAZER_SAVE_SHIPPING_ADDRESS';
export const CART_BLAZER_SAVE_PAYMENT_METHOD = 'CART_BLAZER_SAVE_PAYMENT_METHOD';
export const CART_BLAZER_EMPTY = 'CART_BLAZER_EMPTY';
export const CART_BLAZER_ADD_ITEM_FAIL = 'CART_BLAZER_ADD_ITEM_FAIL';