export const CART_SHERWANI_ADD_ITEM = 'CART_SHERWANI_ADD_ITEM';
export const CART_SHERWANI_REMOVE_ITEM = 'CART_SHERWANI_REMOVE_ITEM';
export const CART_SHERWANI_SAVE_SHIPPING_ADDRESS = 'CART_SHERWANI_SAVE_SHIPPING_ADDRESS';
export const CART_SHERWANI_SAVE_PAYMENT_METHOD = 'CART_SHERWANI_SAVE_PAYMENT_METHOD';
export const CART_SHERWANI_EMPTY = 'CART_SHERWANI_EMPTY';
export const CART_SHERWANI_ADD_ITEM_FAIL = 'CART_SHERWANI_ADD_ITEM_FAIL';