export const CART_KURTAS_ADD_ITEM = 'CART_KURTAS_ADD_ITEM';
export const CART_KURTAS_REMOVE_ITEM = 'CART_KURTAS_REMOVE_ITEM';
export const CART_KURTAS_SAVE_SHIPPING_ADDRESS = 'CART_KURTAS_SAVE_SHIPPING_ADDRESS';
export const CART_KURTAS_SAVE_PAYMENT_METHOD = 'CART_KURTAS_SAVE_PAYMENT_METHOD';
export const CART_KURTAS_EMPTY = 'CART_KURTAS_EMPTY';
export const CART_KURTAS_ADD_ITEM_FAIL = 'CART_KURTAS_ADD_ITEM_FAIL';