export const CART_WOMEN_ADD_ITEM = 'CART_WOMEN_ADD_ITEM';
export const CART_WOMEN_REMOVE_ITEM = 'CART_WOMEN_REMOVE_ITEM';
export const CART_WOMEN_SAVE_SHIPPING_ADDRESS = 'CART_WOMEN_SAVE_SHIPPING_ADDRESS';
export const CART_WOMEN_SAVE_PAYMENT_METHOD = 'CART_WOMEN_SAVE_PAYMENT_METHOD';
export const CART_WOMEN_EMPTY = 'CART_WOMEN_EMPTY';
export const CART_WOMEN_ADD_ITEM_FAIL = 'CART_WOMEN_ADD_ITEM_FAIL';