export const CART_INDIAN_ADD_ITEM = 'CART_INDIAN_ADD_ITEM';
export const CART_INDIAN_REMOVE_ITEM = 'CART_INDIAN_REMOVE_ITEM';
export const CART_INDIAN_SAVE_SHIPPING_ADDRESS = 'CART_INDIAN_SAVE_SHIPPING_ADDRESS';
export const CART_INDIAN_SAVE_PAYMENT_METHOD = 'CART_INDIAN_SAVE_PAYMENT_METHOD';
export const CART_INDIAN_EMPTY = 'CART_INDIAN_EMPTY';
export const CART_INDIAN_ADD_ITEM_FAIL = 'CART_INDIAN_ADD_ITEM_FAIL';