export const CART_SWEATER_ADD_ITEM = 'CART_SWEATER_ADD_ITEM';
export const CART_SWEATER_REMOVE_ITEM = 'CART_SWEATER_REMOVE_ITEM';
export const CART_SWEATER_SAVE_SHIPPING_ADDRESS = 'CART_SWEATER_SAVE_SHIPPING_ADDRESS';
export const CART_SWEATER_SAVE_PAYMENT_METHOD = 'CART_SWEATER_SAVE_PAYMENT_METHOD';
export const CART_SWEATER_EMPTY = 'CART_SWEATER_EMPTY';
export const CART_SWEATER_ADD_ITEM_FAIL = 'CART_SWEATER_ADD_ITEM_FAIL';