export const CART_NEHRU_ADD_ITEM = 'CART_NEHRU_ADD_ITEM';
export const CART_NEHRU_REMOVE_ITEM = 'CART_NEHRU_REMOVE_ITEM';
export const CART_NEHRU_SAVE_SHIPPING_ADDRESS = 'CART_NEHRU_SAVE_SHIPPING_ADDRESS';
export const CART_NEHRU_SAVE_PAYMENT_METHOD = 'CART_NEHRU_SAVE_PAYMENT_METHOD';
export const CART_NEHRU_EMPTY = 'CART_NEHRU_EMPTY';
export const CART_NEHRU_ADD_ITEM_FAIL = 'CART_NEHRU_ADD_ITEM_FAIL';