export const CART_SUIT_ADD_ITEM = 'CART_SUIT_ADD_ITEM';
export const CART_SUIT_REMOVE_ITEM = 'CART_SUIT_REMOVE_ITEM';
export const CART_SUIT_SAVE_SHIPPING_ADDRESS = 'CART_SUIT_SAVE_SHIPPING_ADDRESS';
export const CART_SUIT_SAVE_PAYMENT_METHOD = 'CART_SUIT_SAVE_PAYMENT_METHOD';
export const CART_SUIT_EMPTY = 'CART_SUIT_EMPTY';
export const CART_SUIT_ADD_ITEM_FAIL = 'CART_SUIT_ADD_ITEM_FAIL';