export const CART_JACKET_ADD_ITEM = 'CART_JACKET_ADD_ITEM';
export const CART_JACKET_REMOVE_ITEM = 'CART_JACKET_REMOVE_ITEM';
export const CART_JACKET_SAVE_SHIPPING_ADDRESS = 'CART_JACKET_SAVE_SHIPPING_ADDRESS';
export const CART_JACKET_SAVE_PAYMENT_METHOD = 'CART_JACKET_SAVE_PAYMENT_METHOD';
export const CART_JACKET_EMPTY = 'CART_JACKET_EMPTY';
export const CART_JACKET_ADD_ITEM_FAIL = 'CART_JACKET_ADD_ITEM_FAIL';