export const CART_KID_ADD_ITEM = 'CART_KID_ADD_ITEM';
export const CART_KID_REMOVE_ITEM = 'CART_KID_REMOVE_ITEM';
export const CART_KID_SAVE_SHIPPING_ADDRESS = 'CART_KID_SAVE_SHIPPING_ADDRESS';
export const CART_KID_SAVE_PAYMENT_METHOD = 'CART_KID_SAVE_PAYMENT_METHOD';
export const CART_KID_EMPTY = 'CART_KID_EMPTY';
export const CART_KID_ADD_ITEM_FAIL = 'CART_KID_ADD_ITEM_FAIL';