export const CART_RAINJACKET_ADD_ITEM = 'CART_RAINJACKET_ADD_ITEM';
export const CART_RAINJACKET_REMOVE_ITEM = 'CART_RAINJACKET_REMOVE_ITEM';
export const CART_RAINJACKET_SAVE_SHIPPING_ADDRESS = 'CART_RAINJACKET_SAVE_SHIPPING_ADDRESS';
export const CART_RAINJACKET_SAVE_PAYMENT_METHOD = 'CART_RAINJACKET_SAVE_PAYMENT_METHOD';
export const CART_RAINJACKET_EMPTY = 'CART_RAINJACKET_EMPTY';
export const CART_RAINJACKET_ADD_ITEM_FAIL = 'CART_RAINJACKET_ADD_ITEM_FAIL';