export const CASUALSHIRT_LIST_REQUEST = 'CASUALSHIRT_LIST_REQUEST';
export const CASUALSHIRT_LIST_SUCCESS = 'CASUALSHIRT_LIST_SUCCESS';
export const CASUALSHIRT_LIST_FAIL = 'CASUALSHIRT_LIST_FAIL';

export const CASUALSHIRT_DETAILS_REQUEST = 'CASUALSHIRT_DETAILS_REQUEST';
export const CASUALSHIRT_DETAILS_SUCCESS = 'CASUALSHIRT_DETAILS_SUCCESS';
export const CASUALSHIRT_DETAILS_FAIL = 'CASUALSHIRT_DETAILS_FAIL';

export const CASUALSHIRT_CREATE_REQUEST = 'CASUALSHIRT_CREATE_REQUEST';
export const CASUALSHIRT_CREATE_SUCCESS = 'CASUALSHIRT_CREATE_SUCCESS';
export const CASUALSHIRT_CREATE_FAIL = 'CASUALSHIRT_CREATE_FAIL';
export const CASUALSHIRT_CREATE_RESET = 'CASUALSHIRT_CREATE_RESET';

export const CASUALSHIRT_REVIEW_CREATE_REQUEST = 'CASUALSHIRT_REVIEW_CREATE_REQUEST';
export const CASUALSHIRT_REVIEW_CREATE_SUCCESS = 'CASUALSHIRT_REVIEW_CREATE_SUCCESS';
export const CASUALSHIRT_REVIEW_CREATE_FAIL = 'CASUALSHIRT_REVIEW_CREATE_FAIL';
export const CASUALSHIRT_REVIEW_CREATE_RESET = 'CASUALSHIRT_REVIEW_CREATE_RESET';

export const CASUALSHIRT_UPDATE_REQUEST = 'CASUALSHIRT_UPDATE_REQUEST';
export const CASUALSHIRT_UPDATE_SUCCESS = 'CASUALSHIRT_UPDATE_SUCCESS';
export const CASUALSHIRT_UPDATE_FAIL = 'CASUALSHIRT_UPDATE_FAIL';
export const CASUALSHIRT_UPDATE_RESET = 'CASUALSHIRT_UPDATE_RESET';

export const CASUALSHIRT_DELETE_REQUEST = 'CASUALSHIRT_DELETE_REQUEST';
export const CASUALSHIRT_DELETE_SUCCESS = 'CASUALSHIRT_DELETE_SUCCESS';
export const CASUALSHIRT_DELETE_FAIL = 'CASUALSHIRT_DELETE_FAIL';
export const CASUALSHIRT_DELETE_RESET = 'CASUALSHIRT_DELETE_RESET';

export const CASUALSHIRT_CATEGORY_LIST_REQUEST = 'CASUALSHIRT_CATEGORY_LIST_REQUEST';
export const CASUALSHIRT_CATEGORY_LIST_SUCCESS = 'CASUALSHIRT_CATEGORY_LIST_SUCCESS';
export const CASUALSHIRT_CATEGORY_LIST_FAIL = 'CASUALSHIRT_CATEGORY_LIST_FAIL';


