export const DHOTIS_LIST_REQUEST = 'DHOTIS_LIST_REQUEST';
export const DHOTIS_LIST_SUCCESS = 'DHOTIS_LIST_SUCCESS';
export const DHOTIS_LIST_FAIL = 'DHOTIS_LIST_FAIL';

export const DHOTIS_DETAILS_REQUEST = 'DHOTIS_DETAILS_REQUEST';
export const DHOTIS_DETAILS_SUCCESS = 'DHOTIS_DETAILS_SUCCESS';
export const DHOTIS_DETAILS_FAIL = 'DHOTIS_DETAILS_FAIL';

export const DHOTIS_CREATE_REQUEST = 'DHOTIS_CREATE_REQUEST';
export const DHOTIS_CREATE_SUCCESS = 'DHOTIS_CREATE_SUCCESS';
export const DHOTIS_CREATE_FAIL = 'DHOTIS_CREATE_FAIL';
export const DHOTIS_CREATE_RESET = 'DHOTIS_CREATE_RESET';

export const DHOTIS_REVIEW_CREATE_REQUEST = 'DHOTIS_REVIEW_CREATE_REQUEST';
export const DHOTIS_REVIEW_CREATE_SUCCESS = 'DHOTIS_REVIEW_CREATE_SUCCESS';
export const DHOTIS_REVIEW_CREATE_FAIL = 'DHOTIS_REVIEW_CREATE_FAIL';
export const DHOTIS_REVIEW_CREATE_RESET = 'DHOTIS_REVIEW_CREATE_RESET';

export const DHOTIS_UPDATE_REQUEST = 'DHOTIS_UPDATE_REQUEST';
export const DHOTIS_UPDATE_SUCCESS = 'DHOTIS_UPDATE_SUCCESS';
export const DHOTIS_UPDATE_FAIL = 'DHOTIS_UPDATE_FAIL';
export const DHOTIS_UPDATE_RESET = 'DHOTIS_UPDATE_RESET';

export const DHOTIS_DELETE_REQUEST = 'DHOTIS_DELETE_REQUEST';
export const DHOTIS_DELETE_SUCCESS = 'DHOTIS_DELETE_SUCCESS';
export const DHOTIS_DELETE_FAIL = 'DHOTIS_DELETE_FAIL';
export const DHOTIS_DELETE_RESET = 'DHOTIS_DELETE_RESET';

export const DHOTIS_CATEGORY_LIST_REQUEST = 'DHOTIS_CATEGORY_LIST_REQUEST';
export const DHOTIS_CATEGORY_LIST_SUCCESS = 'DHOTIS_CATEGORY_LIST_SUCCESS';
export const DHOTIS_CATEGORY_LIST_FAIL = 'DHOTIS_CATEGORY_LIST_FAIL';


