export const FORMALSHIRT_LIST_REQUEST = 'FORMALSHIRT_LIST_REQUEST';
export const FORMALSHIRT_LIST_SUCCESS = 'FORMALSHIRT_LIST_SUCCESS';
export const FORMALSHIRT_LIST_FAIL = 'FORMALSHIRT_LIST_FAIL';

export const FORMALSHIRT_DETAILS_REQUEST = 'FORMALSHIRT_DETAILS_REQUEST';
export const FORMALSHIRT_DETAILS_SUCCESS = 'FORMALSHIRTT_DETAILS_SUCCESS';
export const FORMALSHIRT_DETAILS_FAIL = 'FORMALSHIRT_DETAILS_FAIL';

export const FORMALSHIRT_CREATE_REQUEST = 'FORMALSHIRT_CREATE_REQUEST';
export const FORMALSHIRT_CREATE_SUCCESS = 'FORMALSHIRT_CREATE_SUCCESS';
export const FORMALSHIRT_CREATE_FAIL = 'FORMALSHIRT_CREATE_FAIL';
export const FORMALSHIRT_CREATE_RESET = 'FORMALSHIRT_CREATE_RESET';

export const FORMALSHIRT_REVIEW_CREATE_REQUEST = 'FORMALSHIRT_REVIEW_CREATE_REQUEST';
export const FORMALSHIRT_REVIEW_CREATE_SUCCESS = 'FORMALSHIRT_REVIEW_CREATE_SUCCESS';
export const FORMALSHIRT_REVIEW_CREATE_FAIL = 'FORMALSHIRT_REVIEW_CREATE_FAIL';
export const FORMALSHIRT_REVIEW_CREATE_RESET = 'FORMALSHIRT_REVIEW_CREATE_RESET';

export const FORMALSHIRT_UPDATE_REQUEST = 'FORMALSHIRT_UPDATE_REQUEST';
export const FORMALSHIRT_UPDATE_SUCCESS = 'FORMALSHIRT_UPDATE_SUCCESS';
export const FORMALSHIRT_UPDATE_FAIL = 'FORMALSHIRT_UPDATE_FAIL';
export const FORMALSHIRT_UPDATE_RESET = 'FORMALSHIRT_UPDATE_RESET';

export const FORMALSHIRT_DELETE_REQUEST = 'FORMALSHIRT_DELETE_REQUEST';
export const FORMALSHIRT_DELETE_SUCCESS = 'FORMALSHIRT_DELETE_SUCCESS';
export const FORMALSHIRT_DELETE_FAIL = 'FORMALSHIRT_DELETE_FAIL';
export const FORMALSHIRT_DELETE_RESET = 'FORMALSHIRT_DELETE_RESET';

export const FORMALSHIRT_CATEGORY_LIST_REQUEST = 'FORMALSHIRT_CATEGORY_LIST_REQUEST';
export const FORMALSHIRT_CATEGORY_LIST_SUCCESS = 'FORMALSHIRT_CATEGORY_LIST_SUCCESS';
export const FORMALSHIRT_CATEGORY_LIST_FAIL = 'FORMALSHIRT_CATEGORY_LIST_FAIL';


