export const INDIAN_LIST_REQUEST = 'INDIAN_LIST_REQUEST';
export const INDIAN_LIST_SUCCESS = 'INDIAN_LIST_SUCCESS';
export const INDIAN_LIST_FAIL = 'INDIAN_LIST_FAIL';

export const INDIAN_DETAILS_REQUEST = 'INDIAN_DETAILS_REQUEST';
export const INDIAN_DETAILS_SUCCESS = 'INDIAN_DETAILS_SUCCESS';
export const INDIAN_DETAILS_FAIL = 'INDIAN_DETAILS_FAIL';

export const INDIAN_CREATE_REQUEST = 'INDIAN_CREATE_REQUEST';
export const INDIAN_CREATE_SUCCESS = 'INDIAN_CREATE_SUCCESS';
export const INDIAN_CREATE_FAIL = 'INDIAN_CREATE_FAIL';
export const INDIAN_CREATE_RESET = 'INDIAN_CREATE_RESET';

export const INDIAN_REVIEW_CREATE_REQUEST = 'INDIAN_REVIEW_CREATE_REQUEST';
export const INDIAN_REVIEW_CREATE_SUCCESS = 'INDIAN_REVIEW_CREATE_SUCCESS';
export const INDIAN_REVIEW_CREATE_FAIL = 'INDIAN_REVIEW_CREATE_FAIL';
export const INDIAN_REVIEW_CREATE_RESET = 'INDIAN_REVIEW_CREATE_RESET';

export const INDIAN_UPDATE_REQUEST = 'INDIAN_UPDATE_REQUEST';
export const INDIAN_UPDATE_SUCCESS = 'INDIAN_UPDATE_SUCCESS';
export const INDIAN_UPDATE_FAIL = 'INDIAN_UPDATE_FAIL';
export const INDIAN_UPDATE_RESET = 'INDIAN_UPDATE_RESET';

export const INDIAN_DELETE_REQUEST = 'INDIAN_DELETE_REQUEST';
export const INDIAN_DELETE_SUCCESS = 'INDIAN_DELETE_SUCCESS';
export const INDIAN_DELETE_FAIL = 'INDIAN_DELETE_FAIL';
export const INDIAN_DELETE_RESET = 'INDIAN_DELETE_RESET';

export const INDIAN_CATEGORY_LIST_REQUEST = 'INDIAN_CATEGORY_LIST_REQUEST';
export const INDIAN_CATEGORY_LIST_SUCCESS = 'INDIAN_CATEGORY_LIST_SUCCESS';
export const INDIAN_CATEGORY_LIST_FAIL = 'INDIAN_CATEGORY_LIST_FAIL';


