export const JACKET_LIST_REQUEST = 'JACKET_LIST_REQUEST';
export const JACKET_LIST_SUCCESS = 'JACKET_LIST_SUCCESS';
export const JACKET_LIST_FAIL = 'JACKET_LIST_FAIL';

export const JACKET_DETAILS_REQUEST = 'JACKET_DETAILS_REQUEST';
export const JACKET_DETAILS_SUCCESS = 'JACKET_DETAILS_SUCCESS';
export const JACKET_DETAILS_FAIL = 'JACKET_DETAILS_FAIL';

export const JACKET_CREATE_REQUEST = 'JACKET_CREATE_REQUEST';
export const JACKET_CREATE_SUCCESS = 'JACKET_CREATE_SUCCESS';
export const JACKET_CREATE_FAIL = 'JACKET_CREATE_FAIL';
export const JACKET_CREATE_RESET = 'JACKET_CREATE_RESET';

export const JACKET_REVIEW_CREATE_REQUEST = 'JACKET_REVIEW_CREATE_REQUEST';
export const JACKET_REVIEW_CREATE_SUCCESS = 'JACKET_REVIEW_CREATE_SUCCESS';
export const JACKET_REVIEW_CREATE_FAIL = 'JACKET_REVIEW_CREATE_FAIL';
export const JACKET_REVIEW_CREATE_RESET = 'JACKET_REVIEW_CREATE_RESET';

export const JACKET_UPDATE_REQUEST = 'JACKET_UPDATE_REQUEST';
export const JACKET_UPDATE_SUCCESS = 'JACKET_UPDATE_SUCCESS';
export const JACKET_UPDATE_FAIL = 'JACKET_UPDATE_FAIL';
export const JACKET_UPDATE_RESET = 'JACKET_UPDATE_RESET';

export const JACKET_DELETE_REQUEST = 'JACKET_DELETE_REQUEST';
export const JACKET_DELETE_SUCCESS = 'JACKET_DELETE_SUCCESS';
export const JACKET_DELETE_FAIL = 'JACKET_DELETE_FAIL';
export const JACKET_DELETE_RESET = 'JACKET_DELETE_RESET';

export const JACKET_CATEGORY_LIST_REQUEST = 'JACKET_CATEGORY_LIST_REQUEST';
export const JACKET_CATEGORY_LIST_SUCCESS = 'JACKET_CATEGORY_LIST_SUCCESS';
export const JACKET_CATEGORY_LIST_FAIL = 'JACKET_CATEGORY_LIST_FAIL';


