export const KURTAS_LIST_REQUEST = 'KURTAS_LIST_REQUEST';
export const KURTAS_LIST_SUCCESS = 'KURTAS_LIST_SUCCESS';
export const KURTAS_LIST_FAIL = 'KURTAS_LIST_FAIL';

export const KURTAS_DETAILS_REQUEST = 'KURTAS_DETAILS_REQUEST';
export const KURTAS_DETAILS_SUCCESS = 'KURTAS_DETAILS_SUCCESS';
export const KURTAS_DETAILS_FAIL = 'KURTAS_DETAILS_FAIL';

export const KURTAS_CREATE_REQUEST = 'KURTAS_CREATE_REQUEST';
export const KURTAS_CREATE_SUCCESS = 'KURTAS_CREATE_SUCCESS';
export const KURTAS_CREATE_FAIL = 'KURTAS_CREATE_FAIL';
export const KURTAS_CREATE_RESET = 'KURTAS_CREATE_RESET';

export const KURTAS_REVIEW_CREATE_REQUEST = 'KURTAS_REVIEW_CREATE_REQUEST';
export const KURTAS_REVIEW_CREATE_SUCCESS = 'KURTAS_REVIEW_CREATE_SUCCESS';
export const KURTAS_REVIEW_CREATE_FAIL = 'KURTAS_REVIEW_CREATE_FAIL';
export const KURTAS_REVIEW_CREATE_RESET = 'KURTAS_REVIEW_CREATE_RESET';

export const KURTAS_UPDATE_REQUEST = 'KURTAS_UPDATE_REQUEST';
export const KURTAS_UPDATE_SUCCESS = 'KURTAS_UPDATE_SUCCESS';
export const KURTAS_UPDATE_FAIL = 'KURTAS_UPDATE_FAIL';
export const KURTAS_UPDATE_RESET = 'KURTAS_UPDATE_RESET';

export const KURTAS_DELETE_REQUEST = 'KURTAS_DELETE_REQUEST';
export const KURTAS_DELETE_SUCCESS = 'KURTAS_DELETE_SUCCESS';
export const KURTAS_DELETE_FAIL = 'KURTAS_DELETE_FAIL';
export const KURTAS_DELETE_RESET = 'KURTAS_DELETE_RESET';

export const KURTAS_CATEGORY_LIST_REQUEST = 'KURTAS_CATEGORY_LIST_REQUEST';
export const KURTAS_CATEGORY_LIST_SUCCESS = 'KURTAS_CATEGORY_LIST_SUCCESS';
export const KURTAS_CATEGORY_LIST_FAIL = 'KURTAS_CATEGORY_LIST_FAIL';


