export const NEHRU_LIST_REQUEST = 'NEHRU_LIST_REQUEST';
export const NEHRU_LIST_SUCCESS = 'NEHRU_LIST_SUCCESS';
export const NEHRU_LIST_FAIL = 'NEHRU_LIST_FAIL';

export const NEHRU_DETAILS_REQUEST = 'NEHRU_DETAILS_REQUEST';
export const NEHRU_DETAILS_SUCCESS = 'NEHRU_DETAILS_SUCCESS';
export const NEHRU_DETAILS_FAIL = 'NEHRU_DETAILS_FAIL';

export const NEHRU_CREATE_REQUEST = 'NEHRU_CREATE_REQUEST';
export const NEHRU_CREATE_SUCCESS = 'NEHRU_CREATE_SUCCESS';
export const NEHRU_CREATE_FAIL = 'NEHRU_CREATE_FAIL';
export const NEHRU_CREATE_RESET = 'NEHRU_CREATE_RESET';

export const NEHRU_REVIEW_CREATE_REQUEST = 'NEHRU_REVIEW_CREATE_REQUEST';
export const NEHRU_REVIEW_CREATE_SUCCESS = 'NEHRU_REVIEW_CREATE_SUCCESS';
export const NEHRU_REVIEW_CREATE_FAIL = 'NEHRU_REVIEW_CREATE_FAIL';
export const NEHRU_REVIEW_CREATE_RESET = 'NEHRU_REVIEW_CREATE_RESET';

export const NEHRU_UPDATE_REQUEST = 'NEHRU_UPDATE_REQUEST';
export const NEHRU_UPDATE_SUCCESS = 'NEHRU_UPDATE_SUCCESS';
export const NEHRU_UPDATE_FAIL = 'NEHRU_UPDATE_FAIL';
export const NEHRU_UPDATE_RESET = 'NEHRU_UPDATE_RESET';

export const NEHRU_DELETE_REQUEST = 'NEHRU_DELETE_REQUEST';
export const NEHRU_DELETE_SUCCESS = 'NEHRU_DELETE_SUCCESS';
export const NEHRU_DELETE_FAIL = 'NEHRU_DELETE_FAIL';
export const NEHRU_DELETE_RESET = 'NEHRU_DELETE_RESET';

export const NEHRU_CATEGORY_LIST_REQUEST = 'NEHRU_CATEGORY_LIST_REQUEST';
export const NEHRU_CATEGORY_LIST_SUCCESS = 'NEHRU_CATEGORY_LIST_SUCCESS';
export const NEHRU_CATEGORY_LIST_FAIL = 'NEHRU_CATEGORY_LIST_FAIL';


