export const RAINJACKET_LIST_REQUEST = 'RAINJACKET_LIST_REQUEST';
export const RAINJACKET_LIST_SUCCESS = 'RAINJACKET_LIST_SUCCESS';
export const RAINJACKET_LIST_FAIL = 'RAINJACKET_LIST_FAIL';

export const RAINJACKET_DETAILS_REQUEST = 'RAINJACKET_DETAILS_REQUEST';
export const RAINJACKET_DETAILS_SUCCESS = 'RAINJACKET_DETAILS_SUCCESS';
export const RAINJACKET_DETAILS_FAIL = 'RAINJACKET_DETAILS_FAIL';

export const RAINJACKET_CREATE_REQUEST = 'RAINJACKET_CREATE_REQUEST';
export const RAINJACKET_CREATE_SUCCESS = 'RAINJACKET_CREATE_SUCCESS';
export const RAINJACKET_CREATE_FAIL = 'RAINJACKET_CREATE_FAIL';
export const RAINJACKET_CREATE_RESET = 'RAINJACKET_CREATE_RESET';

export const RAINJACKET_REVIEW_CREATE_REQUEST = 'RAINJACKET_REVIEW_CREATE_REQUEST';
export const RAINJACKET_REVIEW_CREATE_SUCCESS = 'RAINJACKET_REVIEW_CREATE_SUCCESS';
export const RAINJACKET_REVIEW_CREATE_FAIL = 'RAINJACKET_REVIEW_CREATE_FAIL';
export const RAINJACKET_REVIEW_CREATE_RESET = 'RAINJACKET_REVIEW_CREATE_RESET';

export const RAINJACKET_UPDATE_REQUEST = 'RAINJACKET_UPDATE_REQUEST';
export const RAINJACKET_UPDATE_SUCCESS = 'RAINJACKET_UPDATE_SUCCESS';
export const RAINJACKET_UPDATE_FAIL = 'RAINJACKET_UPDATE_FAIL';
export const RAINJACKET_UPDATE_RESET = 'RAINJACKET_UPDATE_RESET';

export const RAINJACKET_DELETE_REQUEST = 'RAINJACKET_DELETE_REQUEST';
export const RAINJACKET_DELETE_SUCCESS = 'RAINJACKET_DELETE_SUCCESS';
export const RAINJACKET_DELETE_FAIL = 'RAINJACKET_DELETE_FAIL';
export const RAINJACKET_DELETE_RESET = 'RAINJACKET_DELETE_RESET';

export const RAINJACKET_CATEGORY_LIST_REQUEST = 'RAINJACKET_CATEGORY_LIST_REQUEST';
export const RAINJACKET_CATEGORY_LIST_SUCCESS = 'RAINJACKET_CATEGORY_LIST_SUCCESS';
export const RAINJACKET_CATEGORY_LIST_FAIL = 'RAINJACKET_CATEGORY_LIST_FAIL';