export const SHERWANI_LIST_REQUEST = 'SHERWANI_LIST_REQUEST';
export const SHERWANI_LIST_SUCCESS = 'SHERWANI_LIST_SUCCESS';
export const SHERWANI_LIST_FAIL = 'SHERWANI_LIST_FAIL';

export const SHERWANI_DETAILS_REQUEST = 'SHERWANI_DETAILS_REQUEST';
export const SHERWANI_DETAILS_SUCCESS = 'SHERWANI_DETAILS_SUCCESS';
export const SHERWANI_DETAILS_FAIL = 'SHERWANI_DETAILS_FAIL';

export const SHERWANI_CREATE_REQUEST = 'SHERWANI_CREATE_REQUEST';
export const SHERWANI_CREATE_SUCCESS = 'SHERWANI_CREATE_SUCCESS';
export const SHERWANI_CREATE_FAIL = 'SHERWANI_CREATE_FAIL';
export const SHERWANI_CREATE_RESET = 'SHERWANI_CREATE_RESET';

export const SHERWANI_REVIEW_CREATE_REQUEST = 'SHERWANI_REVIEW_CREATE_REQUEST';
export const SHERWANI_REVIEW_CREATE_SUCCESS = 'SHERWANI_REVIEW_CREATE_SUCCESS';
export const SHERWANI_REVIEW_CREATE_FAIL = 'SHERWANI_REVIEW_CREATE_FAIL';
export const SHERWANI_REVIEW_CREATE_RESET = 'SHERWANI_REVIEW_CREATE_RESET';

export const SHERWANI_UPDATE_REQUEST = 'SHERWANI_UPDATE_REQUEST';
export const SHERWANI_UPDATE_SUCCESS = 'SHERWANI_UPDATE_SUCCESS';
export const SHERWANI_UPDATE_FAIL = 'SHERWANI_UPDATE_FAIL';
export const SHERWANI_UPDATE_RESET = 'SHERWANI_UPDATE_RESET';

export const SHERWANI_DELETE_REQUEST = 'SHERWANI_DELETE_REQUEST';
export const SHERWANI_DELETE_SUCCESS = 'SHERWANI_DELETE_SUCCESS';
export const SHERWANI_DELETE_FAIL = 'SHERWANI_DELETE_FAIL';
export const SHERWANI_DELETE_RESET = 'SHERWANI_DELETE_RESET';

export const SHERWANI_CATEGORY_LIST_REQUEST = 'SHERWANI_CATEGORY_LIST_REQUEST';
export const SHERWANI_CATEGORY_LIST_SUCCESS = 'SHERWANI_CATEGORY_LIST_SUCCESS';
export const SHERWANI_CATEGORY_LIST_FAIL = 'SHERWANI_CATEGORY_LIST_FAIL';


