export const SUIT_LIST_REQUEST = 'SUIT_LIST_REQUEST';
export const SUIT_LIST_SUCCESS = 'SUIT_LIST_SUCCESS';
export const SUIT_LIST_FAIL = 'SUIT_LIST_FAIL';

export const SUIT_DETAILS_REQUEST = 'SUIT_DETAILS_REQUEST';
export const SUIT_DETAILS_SUCCESS = 'SUIT_DETAILS_SUCCESS';
export const SUIT_DETAILS_FAIL = 'SUIT_DETAILS_FAIL';

export const SUIT_CREATE_REQUEST = 'SUIT_CREATE_REQUEST';
export const SUIT_CREATE_SUCCESS = 'SUIT_CREATE_SUCCESS';
export const SUIT_CREATE_FAIL = 'SUIT_CREATE_FAIL';
export const SUIT_CREATE_RESET = 'SUIT_CREATE_RESET';

export const SUIT_REVIEW_CREATE_REQUEST = 'SUIT_REVIEW_CREATE_REQUEST';
export const SUIT_REVIEW_CREATE_SUCCESS = 'SUIT_REVIEW_CREATE_SUCCESS';
export const SUIT_REVIEW_CREATE_FAIL = 'SUIT_REVIEW_CREATE_FAIL';
export const SUIT_REVIEW_CREATE_RESET = 'SUIT_REVIEW_CREATE_RESET';

export const SUIT_UPDATE_REQUEST = 'SUIT_UPDATE_REQUEST';
export const SUIT_UPDATE_SUCCESS = 'SUIT_UPDATE_SUCCESS';
export const SUIT_UPDATE_FAIL = 'SUIT_UPDATE_FAIL';
export const SUIT_UPDATE_RESET = 'SUIT_UPDATE_RESET';

export const SUIT_DELETE_REQUEST = 'SUIT_DELETE_REQUEST';
export const SUIT_DELETE_SUCCESS = 'SUIT_DELETE_SUCCESS';
export const SUIT_DELETE_FAIL = 'SUIT_DELETE_FAIL';
export const SUIT_DELETE_RESET = 'SUIT_DELETE_RESET';

export const SUIT_CATEGORY_LIST_REQUEST = 'SUIT_CATEGORY_LIST_REQUEST';
export const SUIT_CATEGORY_LIST_SUCCESS = 'SUIT_CATEGORY_LIST_SUCCESS';
export const SUIT_CATEGORY_LIST_FAIL = 'SUIT_CATEGORY_LIST_FAIL';