export const SWEATER_LIST_REQUEST = 'SWEATER_LIST_REQUEST';
export const SWEATER_LIST_SUCCESS = 'SWEATER_LIST_SUCCESS';
export const SWEATER_LIST_FAIL = 'SWEATER_LIST_FAIL';

export const SWEATER_DETAILS_REQUEST = 'SWEATER_DETAILS_REQUEST';
export const SWEATER_DETAILS_SUCCESS = 'SWEATER_DETAILS_SUCCESS';
export const SWEATER_DETAILS_FAIL = 'SWEATER_DETAILS_FAIL';

export const SWEATER_CREATE_REQUEST = 'SWEATER_CREATE_REQUEST';
export const SWEATER_CREATE_SUCCESS = 'SWEATER_CREATE_SUCCESS';
export const SWEATER_CREATE_FAIL = 'SWEATER_CREATE_FAIL';
export const SWEATER_CREATE_RESET = 'SWEATER_CREATE_RESET';

export const SWEATER_REVIEW_CREATE_REQUEST = 'SWEATER_REVIEW_CREATE_REQUEST';
export const SWEATER_REVIEW_CREATE_SUCCESS = 'SWEATER_REVIEW_CREATE_SUCCESS';
export const SWEATER_REVIEW_CREATE_FAIL = 'SWEATER_REVIEW_CREATE_FAIL';
export const SWEATER_REVIEW_CREATE_RESET = 'SWEATER_REVIEW_CREATE_RESET';

export const SWEATER_UPDATE_REQUEST = 'SWEATER_UPDATE_REQUEST';
export const SWEATER_UPDATE_SUCCESS = 'SWEATER_UPDATE_SUCCESS';
export const SWEATER_UPDATE_FAIL = 'SWEATER_UPDATE_FAIL';
export const SWEATER_UPDATE_RESET = 'SWEATER_UPDATE_RESET';

export const SWEATER_DELETE_REQUEST = 'SWEATER_DELETE_REQUEST';
export const SWEATER_DELETE_SUCCESS = 'SWEATER_DELETE_SUCCESS';
export const SWEATER_DELETE_FAIL = 'SWEATER_DELETE_FAIL';
export const SWEATER_DELETE_RESET = 'SWEATER_DELETE_RESET';

export const SWEATER_CATEGORY_LIST_REQUEST = 'SWEATER_CATEGORY_LIST_REQUEST';
export const SWEATER_CATEGORY_LIST_SUCCESS = 'SWEATER_CATEGORY_LIST_SUCCESS';
export const SWEATER_CATEGORY_LIST_FAIL = 'SWEATER_CATEGORY_LIST_FAIL';


