export const TSHIRT_LIST_REQUEST = 'TSHIRT_LIST_REQUEST';
export const TSHIRT_LIST_SUCCESS = 'TSHIRT_LIST_SUCCESS';
export const TSHIRT_LIST_FAIL = 'TSHIRT_LIST_FAIL';

export const TSHIRT_DETAILS_REQUEST = 'TSHIRT_DETAILS_REQUEST';
export const TSHIRT_DETAILS_SUCCESS = 'TSHIRT_DETAILS_SUCCESS';
export const TSHIRT_DETAILS_FAIL = 'TSHIRT_DETAILS_FAIL';

export const TSHIRT_CREATE_REQUEST = 'TSHIRT_CREATE_REQUEST';
export const TSHIRT_CREATE_SUCCESS = 'TSHIRT_CREATE_SUCCESS';
export const TSHIRT_CREATE_FAIL = 'TSHIRT_CREATE_FAIL';
export const TSHIRT_CREATE_RESET = 'TSHIRT_CREATE_RESET';

export const TSHIRT_REVIEW_CREATE_REQUEST = 'TSHIRT_REVIEW_CREATE_REQUEST';
export const TSHIRT_REVIEW_CREATE_SUCCESS = 'TSHIRT_REVIEW_CREATE_SUCCESS';
export const TSHIRT_REVIEW_CREATE_FAIL = 'TSHIRT_REVIEW_CREATE_FAIL';
export const TSHIRT_REVIEW_CREATE_RESET = 'TSHIRT_REVIEW_CREATE_RESET';

export const TSHIRT_UPDATE_REQUEST = 'TSHIRT_UPDATE_REQUEST';
export const TSHIRT_UPDATE_SUCCESS = 'TSHIRT_UPDATE_SUCCESS';
export const TSHIRT_UPDATE_FAIL = 'TSHIRT_UPDATE_FAIL';
export const TSHIRT_UPDATE_RESET = 'TSHIRT_UPDATE_RESET';

export const TSHIRT_DELETE_REQUEST = 'TSHIRT_DELETE_REQUEST';
export const TSHIRT_DELETE_SUCCESS = 'TSHIRTT_DELETE_SUCCESS';
export const TSHIRT_DELETE_FAIL = 'TSHIRT_DELETE_FAIL';
export const TSHIRT_DELETE_RESET = 'TSHIRT_DELETE_RESET';

export const TSHIRT_CATEGORY_LIST_REQUEST = 'TSHIRT_CATEGORY_LIST_REQUEST';
export const TSHIRT_CATEGORY_LIST_SUCCESS = 'TSHIRTT_CATEGORY_LIST_SUCCESS';
export const TSHIRT_CATEGORY_LIST_FAIL = 'TSHIRT_CATEGORY_LIST_FAIL';


