export const WOMEN_LIST_REQUEST = 'WOMEN_LIST_REQUEST';
export const WOMEN_LIST_SUCCESS = 'WOMEN_LIST_SUCCESS';
export const WOMEN_LIST_FAIL = 'WOMEN_LIST_FAIL';

export const WOMEN_DETAILS_REQUEST = 'WOMEN_DETAILS_REQUEST';
export const WOMEN_DETAILS_SUCCESS = 'WOMEN_DETAILS_SUCCESS';
export const WOMEN_DETAILS_FAIL = 'WOMEN_DETAILS_FAIL';

export const WOMEN_CREATE_REQUEST = 'WOMEN_CREATE_REQUEST';
export const WOMEN_CREATE_SUCCESS = 'WOMEN_CREATE_SUCCESS';
export const WOMEN_CREATE_FAIL = 'WOMEN_CREATE_FAIL';
export const WOMEN_CREATE_RESET = 'WOMEN_CREATE_RESET';

export const WOMEN_REVIEW_CREATE_REQUEST = 'WOMEN_REVIEW_CREATE_REQUEST';
export const WOMEN_REVIEW_CREATE_SUCCESS = 'WOMEN_REVIEW_CREATE_SUCCESS';
export const WOMEN_REVIEW_CREATE_FAIL = 'WOMEN_REVIEW_CREATE_FAIL';
export const WOMEN_REVIEW_CREATE_RESET = 'WOMEN_REVIEW_CREATE_RESET';

export const WOMEN_UPDATE_REQUEST = 'WOMEN_UPDATE_REQUEST';
export const WOMEN_UPDATE_SUCCESS = 'WOMEN_UPDATE_SUCCESS';
export const WOMEN_UPDATE_FAIL = 'WOMEN_UPDATE_FAIL';
export const WOMEN_UPDATE_RESET = 'WOMEN_UPDATE_RESET';

export const WOMEN_DELETE_REQUEST = 'WOMEN_DELETE_REQUEST';
export const WOMEN_DELETE_SUCCESS = 'WOMEN_DELETE_SUCCESS';
export const WOMEN_DELETE_FAIL = 'WOMEN_DELETE_FAIL';
export const WOMEN_DELETE_RESET = 'WOMEN_DELETE_RESET';

export const WOMEN_CATEGORY_LIST_REQUEST = 'WOMEN_CATEGORY_LIST_REQUEST';
export const WOMEN_CATEGORY_LIST_SUCCESS = 'WOMEN_CATEGORY_LIST_SUCCESS';
export const WOMEN_CATEGORY_LIST_FAIL = 'WOMEN_CATEGORY_LIST_FAIL';