const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],

  womens: [
    {
      _id: '31',
      name: 'Cotton Saree',
      category: 'sarees',
      image: '/images/p12.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '32',
      name: 'Silk Saree',
      category: 'Sarees',
      image: '/images/p91.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '33',
      name: 'Apoorva Saree',
      category: 'sarees',
      image: '/images/p10.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '34',
      name: 'Material Saree',
      category: 'sarees',
      image: '/images/sa4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '35',
      name: 'Kurtha Saree',
      category: 'sarees',
      image: '/images/sa5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
  kids: [
    {
      _id: '21',
      name: 'Little Bansi Full Sleeves',
      category: 'Kids',
      image: '/images/A2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Pantaloon',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '22',
      name: 'Hansa Inskert',
      category: 'Kids',
      image: '/images/kid2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Pantaloon',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '23',
      name: 'Umberalla Harie',
      category: 'Kids',
      image: '/images/kid3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '24',
      name: 'Classic Medie',
      category: 'Kids',
      image: '/images/kid4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Pantaloon',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '25',
      name: 'Angel Medi',
      category: 'Kids',
      image: '/images/kid5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],


  tshirts: [
    {
      _id: '61',
      name: 'line t-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '62',
      name: 'alvi t-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '63',
      name: 'yark t-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '64',
      name: 'ambar t-shirt',
      category: 'Pants',
      image: '/images/shirt4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '65',
      name: 'panku t-shirt',
      category: 'Pants',
      image: '/images/shirt5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

  ],
  sarees: [
    {
      _id: '31',
      name: 'Cotton Saree',
      category: 'sarees',
      image: '/images/p12.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '32',
      name: 'Silk Saree',
      category: 'Sarees',
      image: '/images/p91.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '33',
      name: 'Apoorva Saree',
      category: 'sarees',
      image: '/images/p10.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '34',
      name: 'Material Saree',
      category: 'sarees',
      image: '/images/sa4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '35',
      name: 'Kurtha Saree',
      category: 'sarees',
      image: '/images/sa5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

  ],
  accountin: [
    {
      _id: '20',
      email: 'admins10@email.com'
    },

    {
      _id: '21',
      email: 'sri13@email.com'
    }
  ],


};
export default data;