const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],

  womens: [
    {
      _id: '31',
      name: 'Cotton Saree',
      category: 'sarees',
      image: '/images/p12.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '32',
      name: 'Silk Saree',
      category: 'Sarees',
      image: '/images/p91.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '33',
      name: 'Apoorva Saree',
      category: 'sarees',
      image: '/images/p10.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '34',
      name: 'Material Saree',
      category: 'sarees',
      image: '/images/sa4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '35',
      name: 'Kurtha Saree',
      category: 'sarees',
      image: '/images/sa5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
  kids: [
    {
      _id: '21',
      name: 'Little Bansi Full Sleeves',
      category: 'Kids',
      image: '/images/A2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Pantaloon',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '22',
      name: 'Hansa Inskert',
      category: 'Kids',
      image: '/images/kid2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Pantaloon',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '23',
      name: 'Umberalla Harie',
      category: 'Kids',
      image: '/images/kid3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '24',
      name: 'Classic Medie',
      category: 'Kids',
      image: '/images/kid4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Pantaloon',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '25',
      name: 'Angel Medi',
      category: 'Kids',
      image: '/images/kid5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],


  tshirts: [
    {
      _id: '61',
      name: 'line t-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '62',
      name: 'alvi t-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '63',
      name: 'yark t-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '64',
      name: 'ambar t-shirt',
      category: 'Pants',
      image: '/images/shirt4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '65',
      name: 'panku t-shirt',
      category: 'Pants',
      image: '/images/shirt5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

  ],
  casualshirts: [
    {
      _id: '71',
      name: 'line casual-shirt',
      category: 'Casual Shirts',
      image: '/image/casual5.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '72',
      name: 'alvi casual-shirt',
      category: 'Casual Shirts',
      image: '/image/casual2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '73',
      name: 'yark casual-shirt',
      category: 'Casual Shirts',
      image: '/image/casual3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '74',
      name: 'ambar casual-shirt',
      category: 'Casual Shirts',
      image: '/images/casual4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    

  ],

  formalshirts: [
    {
      _id: '81',
      name: 'line formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '82',
      name: 'alvi formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '83',
      name: 'yark formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '84',
      name: 'ambar formal-shirt',
      category: 'Formal Shirts',
      image: '/image/formal4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    
  ],


  sweaters: [
    {
      _id: '91',
      name: 'anvi sweater',
      category: 'sweaters',
      image: '/image/sw1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '92',
      name: 'aruviya sweater',
      category: 'sweaters',
      image: '/image/sw2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '93',
      name: 'yarky sweater',
      category: 'sweaters',
      image: '/image/sw3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '94',
      name: 'lalachy  sweater',
      category: 'sweater',
      image: '/image/sw4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],

  blazers: [
    {
      _id: '36',
      name: 'alvi blazer',
      category: 'blazers',
      image: '/image/bl1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '37',
      name: 'yogi blazer',
      category: 'blazers',
      image: '/image/bl2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '38',
      name: ' yogo blazer',
      category: 'blazers',
      image: '/image/bl6.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '39',
      name: ' scemy blazer',
      category: 'blazer',
      image: '/image/bl4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '40',
      name: ' formi blazer',
      category: 'blazer',
      image: '/image/bl5.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],
  suits: [
    {
      _id: '41',
      name: 'goodes suit',
      category: 'suits',
      image: '/image/suit1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '42',
      name: 'yogi suit',
      category: 'suits',
      image: '/image/suit2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '43',
      name: ' yahoo suit',
      category: 'suits',
      image: '/image/suit3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '44',
      name: ' scemy suit',
      category: 'suits',
      image: '/image/suit4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '45',
      name: ' formi suit',
      category: 'suits',
      image: '/image/suit7.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],
  rainjackets: [
    {
      _id: '46',
      name: 'woodes rainjacket',
      category: 'rainjackets',
      image: '/image/rain1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '47',
      name: 'yogi rainjacket',
      category: 'rainjackets',
      image: '/image/rain2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '48',
      name: ' yahoo rainjacket',
      category: 'rainjackets',
      image: '/image/rain3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '49',
      name: ' scemy rainjacket',
      category: 'rainjackets',
      image: '/image/rain4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    

  ],


  jackets: [
    {
      _id: '41',
      name: 'anviy jacket',
      category: 'jackets',
      image: '/image/ja1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '42',
      name: 'aruviyas jacket',
      category: 'jackets',
      image: '/image/ja2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '43',
      name: 'yar jacket',
      category: 'jackets',
      image: '/image/ja3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '44',
      name: 'lalachy  jacket',
      category: 'sweater',
      image: '/image/ja4.jpg',
      price: 178,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],
  Saree: [
    {
      _id: "7",
      name: "Cotton Saree",
      category: "Saree",
      image: "/images/p12.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "Silk Saree",
      category: "saree",
      image: "/images/p91.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "9",
      name: "Apoorva Saree",
      category: "saree",
      image: "/images/p10.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "10",
      name: "Material Saree",
      category: "saree",
      image: "/images/sa4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "11",
      name: "Kurtha Saree",
      category: "saree",
      image: "/images/sa5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],

  sarees: [
    {
      _id: '31',
      name: 'Cotton Saree',
      category: 'sarees',
      image: '/images/p12.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '32',
      name: 'Silk Saree',
      category: 'Sarees',
      image: '/images/p91.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '33',
      name: 'Apoorva Saree',
      category: 'sarees',
      image: '/images/p10.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '34',
      name: 'Material Saree',
      category: 'sarees',
      image: '/images/sa4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '35',
      name: 'Kurtha Saree',
      category: 'sarees',
      image: '/images/sa5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

  ],
  accountin: [
    {
      _id: '20',
      email: 'admins10@email.com'
    },

    {
      _id: '21',
      email: 'sri13@email.com'
    }
  ],
  dhotis: [
    {
      _id: '91',
      name: 'goodes dhoti',
      category: 'dhotis',
      image: '/image/dho1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '92',
      name: 'yogily dhoti',
      category: 'dhotis',
      image: '/image/dho2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '92',
      name: ' yahoow dhoti',
      category: 'dhotis',
      image: '/image/dhot3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '93',
      name: ' scemy dhoti',
      category: 'dhotis',
      image: '/image/dho4.jpg',
      price: 978,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '94',
      name: ' formi dhoti',
      category: 'dhotis',
      image: '/image/dho5.jpg',
      price: 578,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],



  indians: [
    {

      name: 'welfy indis',
      category: 'indis',
      image: '/image/in1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'choosy indis',
      category: 'indis',
      image: '/image/in2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: ' yami indis',
      category: 'indis',
      image: '/image/in3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: ' povi indis',
      category: 'indis',
      image: '/image/in4.jpg',
      price: 978,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
   

  ],
  sherwanis: [
    {

      name: 'grandy sherwanis',
      category: 'sherwanis',
      image: '/image/sher1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'choosy sherwanis',
      category: 'sherwanis',
      image: '/image/sher2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: ' yami sherwanis',
      category: 'sherwanis',
      image: '/image/sher4.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: ' povi sherwanis',
      category: 'sherwanis',
      image: '/image/sher5.jpg',
      price: 978,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {

      name: ' waky sherwanis',
      category: 'sherwanis',
      image: '/image/sher7.jpg',
      price: 578,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],

  nehrus: [
    {

      name: 'grandy  nehrus',
      category: ' nehrus',
      image: '/image/nehru1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'pandyy  nehrus',
      category: ' nehrus',
      image: '/image/nehru2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: ' yamiu  nehrus',
      category: 'sherwanis',
      image: '/image/nehru3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: ' povim  nehrus',
      category: ' nehrus',
      image: '/image/nehru4.jpg',
      price: 978,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {

      name: ' waky  nehrus',
      category: ' nehrus',
      image: '/image/nehru5.jpg',
      price: 578,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },


  ],


  kurtas: [
    {

      name: 'grandy  kurtas',
      category: ' kurtas',
      image: '/image/kur1.jpg',
      price: 190,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: 'pandyy  kurtas',
      category: ' kurtas',
      image: '/image/kur2.jpg',
      price: 700,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {

      name: ' yamium  kurtas',
      category: 'kurtas',
      image: '/image/kur3.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
   
    {

      name: ' valviu  kurtas',
      category: 'kurtas',
      image: '/image/kur4.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: ' vapure kurtas',
      category: 'kurtas',
      image: '/image/kur5.jpg',
      price: 220,
      countInStock: 90,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
   

  ],

};
export default data;